name: Build, Test and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.9", "3.10", "3.11"]

      steps:
        - name: Check out code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2

        - uses: pnpm/action-setup@v4.0.0
          with:
            version: 9.0.6

        - name: Setup Node.js environment
          uses: actions/setup-node@v4
          with:
            node-version: "20.5"
            cache: 'pnpm'

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pipenv' #caching pipenv deps

        - name: Install web dependencies
          run: pnpm install

        - name: Install api dependencies
          run: |
            pip install --upgrade pip
            pip install --user pipenv
            pnpm api:install

        - name: Build
          run: pnpm build

        - name: Test
          run: pnpm test:verbose

        - name: Lint web
          run: pnpm --filter web lint

        - name: Lint api
          uses: chartboost/ruff-action@v1
          with:
            src: "./apps/api"
