name: Build, Test and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
      name: Build, Test and Lint
      timeout-minutes: 15
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.8", "3.9", "3.10"]
          node-version: ["16", "18"]

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.32.2

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install web dependencies
          run: pnpm install

        - name: Install api dependencies
          run: pnpm api:install

        - name: Build
          run: pnpm build

        - name: Test
          run: pnpm test:verbose

        - name: Lint
          run: pnpm lint:github